### PR TITLE
(.gitlab-ci.yml) Do not compile with local=true - this is not portable

### PR DESCRIPTION
**Pull request by jdgleaver**
At present, the core on the buildbot is being built with `local=true`, which adds the compilation flag `-march=native`. This is not portable, which means the core will not work on many CPUs.

This trivial PR ensures that the compiled binary is portable. It also ensures that the generated Windows/Linux binaries are stripped (reduces file size by ~90%)

### CODE REVIEW

**Comment by jdgleaver** [comment]
Darn - just deleted this branch by mistake (bash autocompleted the wrong thing...)

Have pushed it again....

**Comment by ds22x** [comment]
I assume this PR would also have to be applied to https://github.com/libretro/bsnes-libretro ?

**Comment by jdgleaver** [comment]
Indeed it does! Well spotted. I'll do that later today.

**Comment by jdgleaver** [comment]
Actually no - I was mistaken. `bsnes-libretro` uses a different makefile for the core build, and it's already correct.

**Comment by ds22x** [comment]
The Libretro branch does, but the Master Branch doesn't (the one that's rebased on upstream).
I know, because I did that rebase myself, and it uses the GNUMakefile for those two builds.

**Comment by ds22x** [comment]
Are you referring to the Master branch, or the Libretro branch?
Because the former is what's currently used for the most recent bsnes cores, not this repository (at least, if all is correct, and it didn't suddenly jump back to the older repository).

**Comment by jdgleaver** [comment]
What a muddle...

These are the bsnes cores that are currently being built via the new infrastructure: https://git.libretro.com/libretro?utf8=%E2%9C%93&filter=bsnes

As you just said, it turns out that this repo isn't being used at all - the `bsnes` core is coming from https://github.com/libretro/bsnes-libretro.git (master branch)

I therefore don't know why this repository still exists, nor do I know why issues for the bsnes-libretro repo are being posted here.

Anyway - thank you for fixing the bsnes-libretro repo. I guess we're all good now...

**Comment by ds22x** [comment]
It has to do with a rebase from a couple of weeks back I did, which I based of the latest upstream, and then transferred ownership of the repo over to Libretro (which subsequently got renamed to bsnes-libretro).
I'd agree that this repo could probably be archived, if only to avoid future confusion.

**Pull request merged**
